import type { Metadata } from "next";
import { Plus_Jakarta_Sans, DM_Sans, Geist } from 'next/font/google';
import "./globals.css";
import { cn } from "@/lib/utils";
import UtilityBar from "@/components/utilityBar";
import Footer from "@/components/Footer";
import Navbar from "@/components/navbar";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});


// Configure the fonts
const dmSans = DM_Sans({
  subsets: ['latin'],
  variable: '--font-inter', // Define a CSS variable name
  display: 'swap',
});

const plusJakarta = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-display',
  weight: ['300', '400', '500', '600', '700', '800'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: {
    default: "UPNG SRIS",
    template: "%s | UPNG SRIS"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", plusJakarta.variable, dmSans.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">
        <UtilityBar />
        <Navbar />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
